name: CI
on: push
jobs:
  test:
    runs-on: macos-15
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Run Tests
        run: |
          mkdir -p test-output
          xcodebuild test -project *.xcodeproj -scheme $(ls *.xcodeproj/xcshareddata/xcschemes/*.xcscheme | head -1 | xargs basename -s .xcscheme) -enableCodeCoverage YES -resultBundlePath test-output/TestResults.xcresult
      - name: Process Test Results
        if: always()
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: test-output/TestResults.xcresult
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output/
