name: CI
on: push
jobs:
  test:
    runs-on: macos-15
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      - name: Install xcbeautify
        run: |
          brew update
          brew install xcbeautify
          xcbeautify --version
      - name: Run Tests
        run: |
          mkdir -p test-output
          swift test 2>&1 | tee test-output/test.log
      - name: Generate JUnit Report
        if: always()
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > test-output/test-results.xml
          echo '<testsuites>' >> test-output/test-results.xml
          echo '<testsuite name="Swift Tests" tests="1">' >> test-output/test-results.xml
          if grep -q "All tests passed" test-output/test.log; then
            echo '<testcase classname="SwiftTests" name="AllTests" time="0"/>' >> test-output/test-results.xml
          else
            echo '<testcase classname="SwiftTests" name="AllTests" time="0">' >> test-output/test-results.xml
            echo '<failure message="Tests failed">' >> test-output/test-results.xml
            cat test-output/test.log | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g' >> test-output/test-results.xml
            echo '</failure>' >> test-output/test-results.xml
            echo '</testcase>' >> test-output/test-results.xml
          fi
          echo '</testsuite>' >> test-output/test-results.xml
          echo '</testsuites>' >> test-output/test-results.xml
          cat test-output/test-results.xml
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output/test-results.xml
      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Swift Tests
          path: test-output/test-results.xml
          reporter: java-junit
          fail-on-error: true
