name: CI

on: push

jobs:
  test:
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      - name: Test
        run: swift test
