name: CI
on: push
jobs:
  test:
    runs-on: macos-15
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      - name: Run Tests
        run: |
          mkdir -p test-output
          swift test --enable-code-coverage --enable-test-discovery 2>&1 | tee test-output/test.log
      - name: Process Test Results
        if: always()
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: test-output/test.log
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output/
