name: CI
on: push
jobs:
  test:
    runs-on: macos-15
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      - name: Install xcbeautify
        run: |
          brew update
          brew install xcbeautify
          xcbeautify --version
      - name: Run Tests
        run: |
          mkdir -p test-output
          swift test --enable-test-discovery 2>&1 | tee test.log | xcbeautify
      - name: Generate JUnit Report
        if: always()
        run: |
          cat test.log | xcbeautify --report junit --report-path test-output/test-results.xml
          ls -la test-output/
          cat test-output/test-results.xml
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-output/test-results.xml
      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Swift Tests
          path: test-output/test-results.xml
          reporter: java-junit
          fail-on-error: true
